 ---
output: pdf_document
---
\begin{document}
\title{Reproducible Research: Peer Assessment 1"}


Loading and preprocessing the data
```{r}
require(ggplot2)
DT <- read.csv(unz('activity.zip', 'activity.csv'))
DT$date <- as.Date(DT$date, '%Y-%M-%d')
```

What is mean total number of steps taken per day?
```{r}
DT.date <- data.frame(steps = tapply(DT$steps, DT$date, sum, na.rm = TRUE))

qplot(data = DT.date, 
      DT.datr$steps, 
      breaks = seq(0, 35000, by = 5000),
      xlab = 'Nuber of Steps',
      ylab = 'Frequency', 
      main = 'Distribution of number of steps taken per day')
mean(DT.datr$steps)
median(DT.datr$steps)
```

What is the average daily activity pattern?
```{r}
DT.interval <- data.frame(steps = tapply(DT$steps, DT$interval, mean, na.rm = TRUE))
ggplot(data = DT.interval, 
        aes(x = row.names(DT.interval), y = DT.interval$steps, group = 1)) +
        geom_line() +
        xlab('Nuber of Steps') +
        ylab('Frequency') + 
        ggtitle('Distribution of number of steps taken per day')
```


Imputing missing values



Are there differences in activity patterns between weekdays and weekends?
\end{document}